server:
  port: 1825

spring:
  application:
    name: Client-mgr

  datasource:
    url: jdbc:mysql://localhost:3306/clientdba
    username: root
    password: passerapasici
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs